storage:
  type: file
  file:
    path: plugins/MinecraftEscape/data.yml

missions:
  collect_diamonds:
    name: "Collect Diamonds"
    description: "Collect 10 diamonds."
    action: "COLLECT"
    target: "DIAMOND"
    amount: 10
    icon: "DIAMOND"
    reward:
      type: "MONEY"
      amount: 100.0
    dependencies: []

  pvp_challenge:
    name: "PvP Challenge"
    description: "Defeat 5 players."
    action: "KILL"
    target: "PLAYER"
    amount: 5
    icon: "DIAMOND_SWORD"
    reward:
      type: "ITEM"
      item: "GOLDEN_APPLE"
      amount: 5
    dependencies:
      - collect_diamonds

  survive_night:
    name: "Survive Night"
    description: "Survive a night without dying."
    action: "SURVIVE"
    target: ""
    amount: 1
    icon: "IRON_PICKAXE"
    reward:
      type: "ITEM"
      item: "IRON_SWORD"
      amount: 1
    dependencies:
      - pvp_challenge

  defeat_zombies:
    name: "Defeat Zombies"
    description: "Defeat 20 zombies."
    action: "KILL"
    target: "ZOMBIE"
    amount: 20
    icon: "ZOMBIE_HEAD"
    reward:
      type: "ITEM"
      item: "DIAMOND_SWORD"
      amount: 1
    dependencies:
      - survive_night
