name: TarkovEscape
main: com.marc.tarkovescape.TarkovEscape
version: 1.0
api-version: 1.16
author: marciismx
commands:
  tarkov:
    description: Basiscommando voor TarkovEscape plugin
    usage: /tarkov <help|loot>
