name: TarkovEscape
version: 1.0
main: com.marc.tarkovescape.TarkovEscape
api-version: 1.16
description: Een Minecraft-plugin geïnspireerd door Escape from Tarkov

commands:
  loot:
    description: Genereer loot of krijg hulp over het gebruik van het loot command.
    usage: /<command> [generate/help]
