name: MinecraftEscape
version: 1.0
main: com.marc.Main
author: Marciismx
api-version: 1.13
description: A Minecraft plugin that adds missions and an economy system.
commands:
  mission:
    description: Opens the mission menu.
    usage: /mission [archive]
  escape:
    description: Provides escape related commands.
    usage: /escape [status|help]
permissions: 
  mission.use:
    description: Allows the player to use mission commands.
    default: true
  escape.use:
    description: Allows the player to use escape commands.
    default: true